import 'dart:ui';

abstract final class AppStrings {
  static const Map<String, String> en = <String, String>{
    'app_name': 'Adz Mavall',
    'skip': 'Skip',
    'onboarding_header': "Let's be\nConnected To\neach Other with\nAdz Mavall",
    'onboarding_header_2':
        'Reach the right\ninfluencers faster\nwith smart\nmatching',
    'onboarding_header_3':
        'Track campaign\nperformance with\nclear live\ninsights',
    'onboarding_title': 'Welcome to the',
    'onboarding_title_2': 'Scale campaigns in',
    'onboarding_title_3': 'Manage results in',
    'onboarding_brand_primary': 'Adz Mavall',
    'onboarding_brand_suffix': ' App',
    'onboarding_description':
        'Connect brands with the right creators,\nlaunch campaigns, and grow together.',
    'onboarding_first_lorem':
        'Connect brands with the right creators, launch campaigns, and grow together — all in one place.',
    'onboarding_description_2':
        'Create better partnerships,\nmove faster,\nand stay organized.',
    'onboarding_description_3':
        'Monitor clicks, engagement,\nand conversion trends\nfrom one dashboard.',
    'onboarding_list_description_1':
        'Build your profile and get matched with campaigns that suit your niche',
    'onboarding_list_description_2':
        'Send proposals, agree on deliverables, and track payments in one place',
    'onboarding_list_description_3':
        'Chat, upload content, and monitor results with a simple dashboard',
    'home_welcome': 'Welcome back, Mahmoud',
    'home_subtitle': 'Track your campaigns and growth in one place',
    'home_active_campaigns': 'Active Campaigns',
    'home_total_reach': 'Total Reach',
    'home_pending_actions': 'Pending Actions',
    'home_recent_campaigns': 'Recent Campaigns',
    'home_quick_actions': 'Quick Actions',
    'home_search_hint': 'Search…',
    'home_welcome_card_title': 'Welcome Aboard',
    'home_welcome_card_body':
        'Sign up today and start creating campaigns to reach your audience with ease.',
    'home_welcome_card_cta': 'Sign up now',
    'home_section_categories': 'Categories',
    'home_show_more': 'Show More',
    'home_section_trending': 'Trending',
    'home_section_featured': 'Top Influencer',
    'home_featured_subtitle': 'Influencers tailored to your brand goals',
    'home_why_title': 'Why Adz Mavall ?',
    'home_why_tab_company': 'Company',
    'home_why_tab_influencer': 'Influencer',
    'home_why_item_1': 'Create your campaign with AI',
    'home_why_item_2': 'Integrate files for influencer',
    'home_why_item_3': 'All your campaigns in one place',
    'home_why_item_4': 'Post- campaigns reports',
    'home_why_item_5': 'Secure and documented payment',
    'home_nav_home': 'Home',
    'influencer_nav_profile': 'Profile',
    'home_nav_orders': 'Orders',
    'home_nav_chat': 'Chat',
    'home_nav_settings': 'Setting',
    'company_nav_home': 'Home',
    'company_nav_chat': 'Chat',
    'company_nav_stars': 'Stars',
    'company_nav_campaigns': 'Campaigns',
    'company_nav_account': 'Account',
    'company_account_section_account': 'Account',
    'company_account_section_general': 'General',
    'company_account_section_support': 'Support',
    'company_account_wallet': 'Wallet',
    'company_account_my_bills': 'My Bills',
    'company_account_language': 'Language',
    'company_account_share_app': 'Share App',
    'company_account_settings': 'Settings',
    'company_account_contact_us': 'Contact Us',
    'company_account_about': 'About',
    'company_account_sign_out': 'Sign out',
    'company_account_sign_out_title': 'Sign out?',
    'company_account_sign_out_body':
        'Are you sure you want to log out ? you will need to login again to access your account',
    'company_account_sign_out_confirm': 'Sign out',
    'company_account_cancel': 'Cancel',
    'company_account_wallet_title': 'Wallet',
    'company_account_available_balance': 'Available Balance',
    'company_account_pending_balance': 'Pending Balance',
    'company_account_total_balance': 'Total Balance',
    'company_account_add_balance': 'Add Balance',
    'company_account_withdraw': 'Withdraw',
    'company_account_transactions': 'Transactions',
    'company_account_payment_hold': 'Payment Hold',
    'company_account_payment_release': 'Payment Release',
    'company_account_bills_title': 'My Bills',
    'company_account_campaign_id': 'Campaign ID',
    'company_account_total_paid': 'Total Paid',
    'company_account_language_search_hint': 'Search Your Message ...',
    'company_account_language_device': 'Device language',
    'company_account_settings_general': 'General',
    'company_account_notification': 'Notification',
    'company_account_location': 'Location',
    'company_account_agreement': 'Adz Mavall unified services Agreement',
    'company_account_delete_account': 'Delete Account',
    'company_account_about_title': 'About App',
    'company_account_privacy_policy': 'Privacy Policy',
    'company_account_privacy_effective': 'Effective Date: 22/16/2025',
    'company_account_privacy_intro':
        '1. Introduction\nWe respect your privacy and are committed to protecting your personal data. This policy explains how we collect, use, and safeguard your information when you use Adz Mavall.\n\n2. Information We Collect\n• Personal Information\n• Usage Data\n• Device and log data\n\n3. How We Use Information\nWe use your data to provide services, improve the app, process payments, and communicate with you about campaigns and account activity.',
    'company_account_contact_title': 'Contact Us',
    'company_account_contact_body':
        'Reach our support team for help with campaigns, billing, or your company account.',
    'company_account_contact_email': 'support@adzmavall.com',
    'company_account_contact_phone': '+966 11 000 0000',
    'company_tab_placeholder_hint':
        'This screen is a placeholder until the real data and API are ready.',
    'company_home_app_title': 'Mavall',
    'company_home_search_hint': 'Search something here…',
    'company_home_under_review_title': 'Your Information Under Review',
    'company_home_under_review_body':
        'Thankyou for Completing Your Account Information\nOur Team is Currently Reviewing it',
    'company_home_section_current_campaign': 'Current Campaign',
    'company_home_section_categories': 'Categories',
    'company_home_section_influencers': 'Influencers',
    'company_home_see_all': 'See All',
    'company_home_currency_sar': 'SR',
    'company_home_campaign_status_completed': 'Completed',
    'company_home_campaign_status_pending': 'New (Pending Approval)',
    'company_campaigns_title': 'Campaigns',
    'company_campaign_filter_all': 'All',
    'company_campaign_filter_completed': 'Completed',
    'company_campaign_filter_cancelled': 'Cancelled',
    'company_campaign_filter_new': 'New',
    'company_campaign_filter_pending': 'Pending',
    'company_campaign_status_cancelled': 'Cancelled',
    'company_campaign_status_pending_client': 'Pending Client Review',
    'company_campaign_status_approved_completed': 'Approved (Completed)',
    'company_campaign_details_title': 'Campaign Details',
    'company_campaign_delivery_date': 'Delivery Date : {date}',
    'company_campaign_brand_name': 'Brand name',
    'company_campaign_website': 'Website',
    'company_campaign_title_field': 'Campaign Title',
    'company_campaign_target_followers': 'Target Followers',
    'company_campaign_target_age': 'Target Audience age Group',
    'company_campaign_proposed_budget': 'Proposed Budget',
    'company_campaign_delivery_date_field': 'Delivery Date',
    'company_campaign_details_field': 'Campaign Details',
    'company_campaign_attached_file': 'Attached File',
    'company_campaign_choose_platform': 'Choose Platform',
    'company_campaign_platform_more': '+ More',
    'company_campaign_type_here': 'Type here...',
    'company_campaign_influencer_details_title': 'Influencer Details',
    'company_campaign_files_count': 'Files ({count})',
    'company_campaign_links': 'Links',
    'company_campaign_order_total': 'Total order',
    'company_campaign_order_listing_fee': 'Listing fee ( 15 % )',
    'company_campaign_order_before_vat': 'Total before vat',
    'company_campaign_order_tax': 'Tax amount ( 15 % )',
    'company_campaign_total_with_tax': 'Total With tax',
    'company_campaign_deposit': 'Deposite',
    'company_campaign_released': 'Released',
    'company_campaign_payment_terms': 'Payment Terms',
    'company_campaign_payment_terms_body':
        'This amount will be available for withdrawal 2 days after the ad is published',
    'company_campaign_learn_more': 'Learn More',
    'company_campaign_price': 'Price',
    'company_create_campaign_title': 'Create Campaign',
    'company_create_save': 'Save',
    'company_create_cancel': 'Cancel',
    'company_create_select': 'Select',
    'company_create_select_all': 'All',
    'company_create_hint_brand': 'Enter brand name',
    'company_create_hint_website': 'Enter URL',
    'company_create_hint_title': 'Enter Campaign Title',
    'company_create_hint_delivery': 'Enter Delivery Date',
    'company_create_confirm_title': 'Confirm Influencer Addition',
    'company_create_confirm_body':
        'This action will send the request for approval and update the order status to pending. Do you want to continue?',
    'company_create_confirm_add': 'Add Influencer',
    'company_create_confirm_skip': 'Skip',
    'company_star_favorite': 'Favorite',
    'company_stars_tab_selected': 'Selected',
    'company_stars_select': 'Select',
    'company_stars_selected': 'Selected',
    'company_stars_next': 'Next',
    'company_stars_top_influencer': 'Content Creators',
    'company_star_cat_sports': 'Sports',
    'company_star_cat_fashion': 'Fashion',
    'company_star_cat_news': 'News',
    'company_stars_filter_title': 'Filter',
    'company_stars_filter_reset': 'Reset',
    'company_stars_filter_apply': 'Apply',
    'company_stars_filter_price': 'Price',
    'company_stars_filter_category': 'Category',
    'company_stars_filter_followers': 'Follower Count',
    'company_stars_filter_platform': 'Platform',
    'company_stars_filter_gender': 'Gender',
    'company_stars_filter_country': 'Country',
    'company_stars_filter_city': 'City',
    'company_stars_filter_tags': 'Tags',
    'company_stars_filter_age': 'Age',
    'company_stars_filter_age_15_20': '15-20 years',
    'company_stars_filter_age_21_25': '21-25 years',
    'company_star_tab_accounts': 'Accounts',
    'company_star_tab_clients': 'Clients',
    'company_star_tab_ad_price': 'Ad Price',
    'company_star_chat': 'Chat with',
    'company_star_email': 'Email',
    'company_star_followers': 'Followers',
    'company_star_coverage': 'Coverage',
    'company_star_video': 'Video',
    'company_star_platform_snapchat': 'Snapchat',
    'company_star_platform_tiktok': 'Tik Tok',
    'company_star_platform_whatsapp': 'Whatsapp',
    'company_star_request_ad': 'Request Ad',
    'company_request_ad_title': 'Request Ad',
    'company_request_ad_delivery': 'Ad Content Delivery Date',
    'company_request_ad_description': 'Short Description',
    'company_request_ad_story': 'Story',
    'company_request_ad_video': 'Video',
    'company_request_ad_post': 'Post',
    'company_request_ad_reel': 'Reel',
    'company_request_ad_payment_methods': 'Payment Methods',
    'company_request_ad_platform_fee': 'Platform fee (15%)',
    'company_request_ad_wallet': 'Wallet',
    'company_request_ad_card': 'Credit / Debit Card',
    'company_request_ad_card_number': 'Card Number',
    'company_request_ad_card_name': 'Card Name',
    'company_request_ad_expiry': 'Expire Date',
    'company_request_ad_pay': 'Pay',
    'company_payment_success_title': 'Your payment has been done successfully',
    'company_payment_success_body':
        'This action will send the request for approval and update the order status to pending. Do you want to continue?',
    'company_payment_success_home': 'Go Home',
    'company_home_category_natural_disaster': 'Natural Disaster',
    'company_home_category_sick_person': 'Sick Person',
    'company_home_category_health_assistance': 'Health Assistance',
    'company_home_category_education_support': 'Education Support',
    'company_home_tag_fashion': 'Fashion',
    'company_home_tag_beauty': 'Beauty',
    'company_home_tag_travel': 'Travel',
    'home_tag_trending_1': 'Beauty',
    'home_tag_trending_2': 'Gaming & Tech',
    'home_tag_trending_3': 'Sports & fitness',
    'home_tag_trending_4': 'Travel & explore',
    'home_tag_trending_5': 'Food',
    'home_tag_trending_6': 'E-learning',
    'home_category_1': 'Lifestyle',
    'home_category_2': 'Gaming',
    'home_category_3': 'Beauty',
    'home_category_4': 'Music',
    'home_influencers_count': '2.1k+ creators',
    'home_starting_from': 'Starting from',
    'home_hire': 'Hire',
    'splash_title': 'Adz Mavall',
    'auth_choose_account_title': 'Choose your account type',
    'auth_choose_account_subtitle':
        'Select what best describes you to personalize your experience and features',
    'auth_account_influencer_title': 'Influencer',
    'auth_account_influencer_desc':
        'Create your profile, get discovered, and collaborate with brands',
    'auth_account_company_title': 'Company',
    'auth_account_company_desc':
        'Find creators, launch campaigns, and manage collaborations in one place',
    'auth_next': 'Next',
    'auth_skip_setup': 'Skip setup and enter the app',
    'auth_verification_title': 'Verification',
    'auth_verification_subtitle':
        'We have sent 4 digits verification code to Your Phone {phone}',
    'auth_resend_code': 'Resend Code ?',
    'auth_send_via_whatsapp': 'Send Verification Code via Whatsapp',
    'auth_demo_phone': '+966555555555',
    'auth_phone_title': 'Enter your phone number',
    'auth_phone_subtitle':
        'We will send a 4-digit verification code to this number',
    'auth_phone_field_label': 'Phone number',
    'auth_phone_hint': '55 555 5566',
    'profile_create_account': 'Create Your Account',
    'profile_create_account_subtitle':
        'Complete your profile so brands can discover you.',
    'profile_submit': 'Submit Profile',
    'profile_account_type_title': 'Account Type',
    'profile_account_type_subtitle':
        'Your selected account type for this registration flow.',
    'profile_user_type_title': 'User Type',
    'profile_creator_type_title': 'Creator Type',
    'profile_creator_type_subtitle':
        'Choose your creator type to continue registration.',
    'profile_select_category_label': 'Select Category',
    'profile_influencer': 'Influencer',
    'profile_company': 'Company',
    'company_registration_success_title':
        'Your Request has been received successfully',
    'company_registration_success_subtitle':
        'Please wait for the approval of your account by the administration',
    'company_registration_home_cta': 'Home page',
    'profile_model': 'Model',
    'profile_collage': 'Collage',
    'profile_ugc': 'UGC',
    'profile_gender_label': 'Gender',
    'profile_gender_male': 'Male',
    'profile_gender_female': 'Female',
    'profile_basic_title': 'Basic Information',
    'profile_basic_subtitle': 'Add the details that identify your account.',
    'profile_name': 'Name',
    'profile_name_hint': 'Enter name',
    'profile_full_name_arabic': 'Full Name (Arabic)',
    'profile_full_name_arabic_hint': 'Enter name',
    'profile_mawthoq_certificate': 'Mawthoq Certificate Number',
    'profile_mawthoq_certificate_hint': 'Enter certificate number',
    'profile_full_name': 'Full Name',
    'profile_full_name_hint': 'Enter your full name',
    'profile_email': 'Email',
    'profile_email_hint': 'name@example.com',
    'profile_age': 'Age',
    'profile_age_hint': '25',
    'profile_country': 'Country',
    'profile_country_saudi': 'Saudi Arabia',
    'profile_country_uae': 'United Arab Emirates',
    'profile_country_egypt': 'Egypt',
    'profile_city': 'City',
    'profile_city_hint': 'Select city',
    'profile_contact_label': 'Contact',
    'profile_select_hint': 'Select',
    'profile_required_error': 'This field is required',
    'profile_email_error': 'Enter a valid email address',
    'profile_categories_title': 'Categories',
    'profile_categories_subtitle':
        'Choose the categories that best describe your content.',
    'profile_main_category': 'Main Category',
    'profile_category_fashion': 'Fashion',
    'profile_category_beauty': 'Beauty',
    'profile_category_food': 'Food',
    'profile_category_travel': 'Travel',
    'profile_category_tech': 'Tech',
    'profile_category_sports': 'Sports',
    'profile_details_title': 'Influencer Details',
    'profile_details_subtitle': 'Add your district, direction, and city.',
    'profile_model_details_title': 'Model Details',
    'profile_collage_details_title': 'Collage Details',
    'profile_ugc_details_title': 'UGC Details',
    'profile_nationality': 'Nationality',
    'profile_nationality_hint': 'Select category',
    'profile_size': 'Size',
    'profile_size_hint': 'Select category',
    'profile_skin_tone': 'Skin Tone',
    'profile_skin_tone_hint': 'Select category',
    'profile_session_rate_per_hour_sar': 'Session Rate Per Hour (SAR)',
    'profile_height_cm': 'Height (cm)',
    'profile_height_cm_hint': 'Enter height',
    'profile_weight_kg': 'Weight (kg)',
    'profile_weight_kg_hint': 'Enter weight',
    'profile_skin': 'Skin',
    'profile_skin_hint': 'Select category',
    'profile_eye_color': 'Eye Color',
    'profile_eye_color_hint': 'Select category',
    'profile_shoes_size': 'Shoes Size',
    'profile_shoes_size_hint': 'Enter shoes size',
    'profile_modeling_experience': 'Experience Year in Modeling',
    'profile_modeling_experience_hint': 'Enter years',
    'profile_price_per_second_sar': 'Price Per Second (SAR)',
    'profile_video_price_sar_short': 'Video Price (SAR)',
    'profile_delivery_time_from_arrival': 'Delivery Time From Product Arrival',
    'profile_offer_your_works': 'Offer Your Works',
    'profile_voice_over': 'Voice Over',
    'profile_use_hook': 'Use Hook',
    'profile_hair_visible': 'Hair Visible',
    'profile_face_visible': 'Face Visible',
    'profile_have_visible': 'Have Visible',
    'profile_show_full_body': 'Show Full Body',
    'profile_district': 'District',
    'profile_district_hint': 'Enter district',
    'profile_direction': 'Direction',
    'profile_direction_hint': 'Select direction',
    'profile_direction_opt_north': 'North',
    'profile_direction_opt_south': 'South',
    'profile_direction_opt_east': 'East',
    'profile_direction_opt_west': 'West',
    'profile_direction_opt_central': 'Central',
    'profile_city_opt_riyadh': 'Riyadh',
    'profile_city_opt_jeddah': 'Jeddah',
    'profile_city_opt_dubai': 'Dubai',
    'profile_city_opt_doha': 'Doha',
    'profile_city_opt_cairo': 'Cairo',
    'profile_bio': 'Bio',
    'profile_bio_hint': 'Write a short bio about your content',
    'profile_language': 'Content Language',
    'profile_language_arabic': 'Arabic',
    'profile_language_english': 'English',
    'profile_language_both': 'Arabic and English',
    'profile_social_title': 'Social Media Accounts & Pricing',
    'profile_social_subtitle':
        'Add your social accounts and set prices for each platform.',
    'profile_username_handle': 'Username / Handle',
    'profile_username_handle_hint': '@...',
    'profile_story_price_sar': 'Story Price (SAR)',
    'profile_video_price_sar': 'Video Price (SAR)',
    'profile_reel_price_sar': 'Reel Price (SAR)',
    'profile_post_price_sar': 'Post Price (SAR)',
    'profile_price_enter_hint': 'Enter',
    'profile_works_portfolio_title': 'Works & Portfolio',
    'profile_works_portfolio_subtitle':
        'Choose a creator profile to preview its dynamic fields.',
    'profile_portfolio_upload_area_title': 'Portfolio Upload Area',
    'profile_portfolio_upload_area_desc':
        'Add sample videos, images, or campaign references for preview purposes.',
    'profile_browse_files': 'Browse Files',
    'profile_file_skipped_large_one':
        'One file was skipped (over 5 MB per file).',
    'profile_file_skipped_large_many':
        '{count} files were skipped (over 5 MB per file).',
    'profile_clients_title': 'Clients',
    'profile_clients_subtitle':
        'Choose a creator profile to preview its dynamic fields.',
    'profile_clients_empty_title': 'No Client Data Available Yet',
    'profile_add_client': 'Add Client',
    'profile_add_clients_sheet_title': 'Add Clients',
    'profile_search_people_hint': 'Search People',
    'profile_add_clients_with_count': 'Add ({count}) Clients',
    'profile_client_cat_sports': 'Sports',
    'profile_client_cat_entertainment': 'Entertainment',
    'profile_client_cat_beverage': 'Beverage',
    'profile_client_cat_food': 'Food',
    'profile_client_cat_clothing': 'Clothing',
    'profile_client_cat_tech': 'Tech',
    'profile_followers': 'Followers',
    'profile_post_price': 'Post Price',
    'profile_story_price': 'Story Price',
    'profile_reel_price': 'Reel Price',
    'profile_currency_hint': 'SAR',
    'profile_platform_instagram': 'Instagram',
    'profile_platform_snapchat': 'Snapchat',
    'profile_platform_tiktok': 'TikTok',
    'profile_platform': 'Platform',
    'profile_media_title': 'Work Portfolio',
    'profile_media_subtitle':
        'Add temporary samples now; upload handling will connect to the API later.',
    'profile_work_upload_title': 'Upload Work Samples',
    'profile_work_upload_desc':
        'Add images or videos that represent your work.',
    'profile_add_sample': 'Add Sample',
    'profile_others_title': 'Others',
    'profile_preferred_collaboration': 'Preferred Collaboration',
    'profile_preferred_contact': 'Preferred Contact Method',
    'profile_collab_paid': 'Paid',
    'profile_collab_barter': 'Barter',
    'profile_collab_both': 'Both',
    'profile_contact_whatsapp': 'WhatsApp',
    'profile_contact_email': 'Email',
    'profile_contact_phone': 'Phone',
    'profile_ads_title': 'Ads',
    'profile_ads_subtitle':
        'Choose a creator profile to preview its dynamic fields.',
    'profile_ads_upload_title': 'Upload Ads',
    'profile_ads_upload_desc': 'Add ad examples for brands to review.',
    'profile_ads_upload_dialog_title': 'Upload ads',
    'profile_ads_dialog_body':
        'Pick one or more video files from your device. They appear as previews below.',
    'profile_ads_browse_videos': 'Browse videos',
    'profile_ads_add_more': 'Add more',
    'profile_add_ad': 'Add ADS',
    'profile_cancel': 'Cancel',
  };

  static const Map<String, String> ar = <String, String>{
    'app_name': 'آدز مافال',
    'skip': 'تخطي',
    'onboarding_header': 'لنكن\nمتصلين معًا\nمن خلال\nAdz Mavall',
    'onboarding_header_2':
        'صل إلى المؤثرين\nالمناسبين بشكل أسرع\nبمطابقة\nذكية',
    'onboarding_header_3': 'تابع أداء الحملات\nبمؤشرات مباشرة\nوواضحة\nدائمًا',
    'onboarding_title': 'مرحبا بك في',
    'onboarding_title_2': 'نمّي حملاتك عبر',
    'onboarding_title_3': 'أدر النتائج في',
    'onboarding_brand_primary': 'Adz Mavall',
    'onboarding_brand_suffix': ' التطبيق',
    'onboarding_description':
        'نوصّل العلامات بالمبدعين المناسبين،\nنطلق الحملات، وننمو معًا.',
    'onboarding_first_lorem':
        'نوصّل العلامات بالمبدعين المناسبين، نطلق الحملات، وننمو معًا — كل ده في مكان واحد.',
    'onboarding_description_2':
        'أنشئ شراكات أقوى،\nتحرك أسرع،\nوابقي كل شيء منظمًا.',
    'onboarding_description_3':
        'راقب النقرات والتفاعل\nومعدلات التحويل\nمن لوحة تحكم واحدة.',
    'onboarding_list_description_1':
        'أنشئ ملفك الشخصي وتطابق مع الحملات المناسبة لتخصصك.',
    'onboarding_list_description_2':
        'أرسل العروض واتفق على المتطلبات وتابع المدفوعات في مكان واحد.',
    'onboarding_list_description_3':
        'تحدث، ارفع المحتوى، وتابع النتائج من خلال لوحة بسيطة.',
    'home_welcome': 'مرحبًا بعودتك، محمود',
    'home_subtitle': 'تابع حملاتك ونموك من مكان واحد',
    'home_active_campaigns': 'الحملات النشطة',
    'home_total_reach': 'إجمالي الوصول',
    'home_pending_actions': 'الإجراءات المعلقة',
    'home_recent_campaigns': 'أحدث الحملات',
    'home_quick_actions': 'إجراءات سريعة',
    'home_search_hint': 'ابحث…',
    'home_welcome_card_title': 'أهلاً بك',
    'home_welcome_card_body':
        'سجّل اليوم وابدأ إنشاء الحملات للوصول إلى جمهورك بسهولة.',
    'home_welcome_card_cta': ' سجل الآن',
    'home_section_categories': 'الفئات',
    'home_show_more': 'عرض المزيد',
    'home_section_trending': 'الشائع',
    'home_section_featured': 'أفضل المؤثرين',
    'home_featured_subtitle': 'مؤثرون يناسبون أهداف علامتك',
    'home_why_title': 'لماذا آدز مافال؟',
    'home_why_tab_company': 'الشركات',
    'home_why_tab_influencer': 'المؤثرون',
    'home_why_item_1': 'أنشئ حملتك بالذكاء الاصطناعي',
    'home_why_item_2': 'ادمج ملفاتك مع المؤثر',
    'home_why_item_3': 'كل حملاتك في مكان واحد',
    'home_why_item_4': 'تقارير ما بعد الحملة',
    'home_why_item_5': 'دفع آمن وموثّق',
    'home_nav_home': 'الرئيسية',
    'influencer_nav_profile': 'الملف',
    'home_nav_orders': 'الطلبات',
    'home_nav_chat': 'الدردشة',
    'home_nav_settings': 'الإعدادات',
    'company_nav_home': 'الرئيسية',
    'company_nav_chat': 'المحادثة',
    'company_nav_stars': 'النجوم',
    'company_nav_campaigns': 'الحملات',
    'company_nav_account': 'الحساب',
    'company_account_section_account': 'الحساب',
    'company_account_section_general': 'عام',
    'company_account_section_support': 'الدعم',
    'company_account_wallet': 'المحفظة',
    'company_account_my_bills': 'فواتيري',
    'company_account_language': 'اللغة',
    'company_account_share_app': 'مشاركة التطبيق',
    'company_account_settings': 'الإعدادات',
    'company_account_contact_us': 'اتصل بنا',
    'company_account_about': 'حول التطبيق',
    'company_account_sign_out': 'تسجيل الخروج',
    'company_account_sign_out_title': 'تسجيل الخروج؟',
    'company_account_sign_out_body':
        'هل أنت متأكد أنك تريد تسجيل الخروج؟ ستحتاج إلى تسجيل الدخول مرة أخرى للوصول إلى حسابك',
    'company_account_sign_out_confirm': 'تسجيل الخروج',
    'company_account_cancel': 'إلغاء',
    'company_account_wallet_title': 'المحفظة',
    'company_account_available_balance': 'الرصيد المتاح',
    'company_account_pending_balance': 'الرصيد المعلق',
    'company_account_total_balance': 'إجمالي الرصيد',
    'company_account_add_balance': 'إضافة رصيد',
    'company_account_withdraw': 'سحب',
    'company_account_transactions': 'المعاملات',
    'company_account_payment_hold': 'تعليق الدفع',
    'company_account_payment_release': 'إطلاق الدفع',
    'company_account_bills_title': 'فواتيري',
    'company_account_campaign_id': 'معرّف الحملة',
    'company_account_total_paid': 'إجمالي المدفوع',
    'company_account_language_search_hint': 'ابحث في رسالتك ...',
    'company_account_language_device': 'لغة الجهاز',
    'company_account_settings_general': 'عام',
    'company_account_notification': 'الإشعارات',
    'company_account_location': 'الموقع',
    'company_account_agreement': 'اتفاقية خدمات آدز مافال الموحدة',
    'company_account_delete_account': 'حذف الحساب',
    'company_account_about_title': 'حول التطبيق',
    'company_account_privacy_policy': 'سياسة الخصوصية',
    'company_account_privacy_effective': 'تاريخ السريان: 22/16/2025',
    'company_account_privacy_intro':
        '1. المقدمة\nنحترم خصوصيتك ونلتزم بحماية بياناتك الشخصية. توضح هذه السياسة كيفية جمع معلوماتك واستخدامها وحمايتها عند استخدام آدز مافال.\n\n2. المعلومات التي نجمعها\n• معلومات شخصية\n• بيانات الاستخدام\n• بيانات الجهاز والسجلات\n\n3. كيفية استخدام المعلومات\nنستخدم بياناتك لتقديم الخدمات وتحسين التطبيق ومعالجة المدفوعات والتواصل معك بشأن الحملات ونشاط الحساب.',
    'company_account_contact_title': 'اتصل بنا',
    'company_account_contact_body':
        'تواصل مع فريق الدعم للمساعدة في الحملات أو الفوترة أو حساب شركتك.',
    'company_account_contact_email': 'support@adzmavall.com',
    'company_account_contact_phone': '+966 11 000 0000',
    'company_home_app_title': 'Mavall',
    'company_home_search_hint': 'ابحث هنا…',
    'company_home_under_review_title': 'بياناتك قيد المراجعة',
    'company_home_under_review_body':
        'شكرًا لإكمال معلومات حسابك\nفريقنا يقوم بمراجعته الآن',
    'company_home_section_current_campaign': 'الحملة الحالية',
    'company_home_section_categories': 'الفئات',
    'company_home_section_influencers': 'المؤثرون',
    'company_home_see_all': 'عرض الكل',
    'company_home_currency_sar': 'ر.س',
    'company_home_campaign_status_completed': 'مكتملة',
    'company_home_campaign_status_pending': 'جديدة (بانتظار الموافقة)',
    'company_campaigns_title': 'الحملات',
    'company_campaign_filter_all': 'الكل',
    'company_campaign_filter_completed': 'مكتملة',
    'company_campaign_filter_cancelled': 'ملغاة',
    'company_campaign_filter_new': 'جديدة',
    'company_campaign_filter_pending': 'قيد الانتظار',
    'company_campaign_status_cancelled': 'ملغاة',
    'company_campaign_status_pending_client': 'بانتظار مراجعة العميل',
    'company_campaign_status_approved_completed': 'معتمدة (مكتملة)',
    'company_campaign_details_title': 'تفاصيل الحملة',
    'company_campaign_delivery_date': 'تاريخ التسليم : {date}',
    'company_campaign_brand_name': 'اسم العلامة',
    'company_campaign_website': 'الموقع',
    'company_campaign_title_field': 'عنوان الحملة',
    'company_campaign_target_followers': 'المتابعون المستهدفون',
    'company_campaign_target_age': 'الفئة العمرية المستهدفة',
    'company_campaign_proposed_budget': 'الميزانية المقترحة',
    'company_campaign_delivery_date_field': 'تاريخ التسليم',
    'company_campaign_details_field': 'تفاصيل الحملة',
    'company_campaign_attached_file': 'ملف مرفق',
    'company_campaign_choose_platform': 'اختر المنصة',
    'company_campaign_platform_more': '+ المزيد',
    'company_campaign_type_here': 'اكتب هنا...',
    'company_campaign_influencer_details_title': 'تفاصيل المؤثر',
    'company_campaign_files_count': 'الملفات ({count})',
    'company_campaign_links': 'الروابط',
    'company_campaign_order_total': 'إجمالي الطلب',
    'company_campaign_order_listing_fee': 'رسوم الإدراج ( 15 % )',
    'company_campaign_order_before_vat': 'الإجمالي قبل الضريبة',
    'company_campaign_order_tax': 'قيمة الضريبة ( 15 % )',
    'company_campaign_total_with_tax': 'الإجمالي مع الضريبة',
    'company_campaign_deposit': 'العربون',
    'company_campaign_released': 'المُفرج عنه',
    'company_campaign_payment_terms': 'شروط الدفع',
    'company_campaign_payment_terms_body':
        'سيكون هذا المبلغ متاحًا للسحب بعد يومين من نشر الإعلان',
    'company_campaign_learn_more': 'اعرف المزيد',
    'company_campaign_price': 'السعر',
    'company_create_campaign_title': 'إنشاء حملة',
    'company_create_save': 'حفظ',
    'company_create_cancel': 'إلغاء',
    'company_create_select': 'اختر',
    'company_create_select_all': 'الكل',
    'company_create_hint_brand': 'أدخل اسم العلامة',
    'company_create_hint_website': 'أدخل الرابط',
    'company_create_hint_title': 'أدخل عنوان الحملة',
    'company_create_hint_delivery': 'أدخل تاريخ التسليم',
    'company_create_confirm_title': 'تأكيد إضافة المؤثر',
    'company_create_confirm_body':
        'سيتم إرسال الطلب للموافقة وتحديث حالة الطلب إلى قيد الانتظار. هل تريد المتابعة؟',
    'company_create_confirm_add': 'إضافة مؤثر',
    'company_create_confirm_skip': 'تخطي',
    'company_star_favorite': 'المفضلة',
    'company_stars_tab_selected': 'المحدد',
    'company_stars_select': 'اختيار',
    'company_stars_selected': 'محدد',
    'company_stars_next': 'التالي',
    'company_stars_top_influencer': 'صناع المحتوى',
    'company_star_cat_sports': 'رياضة',
    'company_star_cat_fashion': 'أزياء',
    'company_star_cat_news': 'أخبار',
    'company_stars_filter_title': 'تصفية',
    'company_stars_filter_reset': 'إعادة تعيين',
    'company_stars_filter_apply': 'تطبيق',
    'company_stars_filter_price': 'السعر',
    'company_stars_filter_category': 'الفئة',
    'company_stars_filter_followers': 'عدد المتابعين',
    'company_stars_filter_platform': 'المنصة',
    'company_stars_filter_gender': 'الجنس',
    'company_stars_filter_country': 'الدولة',
    'company_stars_filter_city': 'المدينة',
    'company_stars_filter_tags': 'الوسوم',
    'company_stars_filter_age': 'العمر',
    'company_stars_filter_age_15_20': '15-20 سنة',
    'company_stars_filter_age_21_25': '21-25 سنة',
    'company_star_tab_accounts': 'الحسابات',
    'company_star_tab_clients': 'العملاء',
    'company_star_tab_ad_price': 'أسعار الإعلان',
    'company_star_chat': 'محادثة',
    'company_star_email': 'بريد',
    'company_star_followers': 'متابع',
    'company_star_coverage': 'تغطية',
    'company_star_video': 'فيديو',
    'company_star_platform_snapchat': 'سناب شات',
    'company_star_platform_tiktok': 'تيك توك',
    'company_star_platform_whatsapp': 'واتساب',
    'company_star_request_ad': 'طلب إعلان',
    'company_request_ad_title': 'طلب إعلان',
    'company_request_ad_delivery': 'تاريخ تسليم محتوى الإعلان',
    'company_request_ad_description': 'وصف قصير',
    'company_request_ad_story': 'قصة',
    'company_request_ad_video': 'فيديو',
    'company_request_ad_post': 'منشور',
    'company_request_ad_reel': 'ريل',
    'company_request_ad_payment_methods': 'طرق الدفع',
    'company_request_ad_platform_fee': 'رسوم المنصة (15%)',
    'company_request_ad_wallet': 'المحفظة',
    'company_request_ad_card': 'بطاقة ائتمان / خصم',
    'company_request_ad_card_number': 'رقم البطاقة',
    'company_request_ad_card_name': 'اسم البطاقة',
    'company_request_ad_expiry': 'تاريخ الانتهاء',
    'company_request_ad_pay': 'ادفع',
    'company_payment_success_title': 'تم الدفع بنجاح',
    'company_payment_success_body':
        'سيتم إرسال الطلب للموافقة وتحديث حالة الطلب إلى قيد الانتظار. هل تريد المتابعة؟',
    'company_payment_success_home': 'الذهاب للرئيسية',
    'company_home_category_natural_disaster': 'كوارث طبيعية',
    'company_home_category_sick_person': 'مرضى',
    'company_home_category_health_assistance': 'مساعدات صحية',
    'company_home_category_education_support': 'دعم تعليمي',
    'company_home_tag_fashion': 'أزياء',
    'company_home_tag_beauty': 'تجميل',
    'company_home_tag_travel': 'سفر',
    'company_tab_placeholder_hint':
        'هذه الشاشة مؤقتة إلى أن يكون المحتوى الحقيقي والواجهة البرمجية جاهزة.',
    'home_tag_trending_1': 'جمال',
    'home_tag_trending_2': 'ألعاب وتقنية',
    'home_tag_trending_3': 'رياضة',
    'home_tag_trending_4': 'سفر',
    'home_tag_trending_5': 'طعام',
    'home_tag_trending_6': 'تعليم',
    'home_category_1': 'نمط حياة',
    'home_category_2': 'ألعاب',
    'home_category_3': 'جمال',
    'home_category_4': 'موسيقى',
    'home_influencers_count': '+2.1 ألف مبدع',
    'home_starting_from': 'يبدأ من',
    'home_hire': 'توظيف',
    'splash_title': 'آدز مافال',
    'auth_choose_account_title': 'اختر نوع حسابك',
    'auth_choose_account_subtitle':
        'اختر ما يصفك بشكل أفضل لتخصيص تجربتك والميزات المناسبة لك',
    'auth_account_influencer_title': 'مؤثر',
    'auth_account_influencer_desc':
        'أنشئ ملفك، كن أكثر ظهورًا، وتعاون مع العلامات التجارية',
    'auth_account_company_title': 'شركة',
    'auth_account_company_desc':
        'اعثر على المبدعين، أطلق الحملات، وأدر التعاون من مكان واحد',
    'auth_next': 'التالي',
    'auth_skip_setup': 'تخطي الإعداد والدخول للتطبيق',
    'auth_verification_title': 'التحقق',
    'auth_verification_subtitle':
        'أرسلنا رمزًا مكوّنًا من 4 أرقام إلى هاتفك {phone}',
    'auth_resend_code': 'إعادة إرسال الرمز؟',
    'auth_send_via_whatsapp': 'إرسال رمز التحقق عبر واتساب',
    'auth_demo_phone': '+966555555555',
    'auth_phone_title': 'أدخل رقم هاتفك',
    'auth_phone_subtitle': 'سنرسل رمزًا مكوّنًا من 4 أرقام إلى هذا الرقم',
    'auth_phone_field_label': 'رقم الهاتف',
    'auth_phone_hint': '55 555 5566',
    'profile_create_account': 'أنشئ حسابك',
    'profile_create_account_subtitle':
        'أكمل ملفك حتى تتمكن العلامات من اكتشافك.',
    'profile_submit': 'إكمال الملف',
    'profile_account_type_title': 'نوع الحساب',
    'profile_account_type_subtitle': 'نوع الحساب المختار لهذا المسار.',
    'profile_user_type_title': 'نوع المستخدم',
    'profile_creator_type_title': 'نوع المبدع',
    'profile_creator_type_subtitle': 'اختر نوع المبدع لمتابعة التسجيل.',
    'profile_select_category_label': 'اختر التصنيف',
    'profile_influencer': 'مؤثر',
    'profile_company': 'شركة',
    'company_registration_success_title': 'تم استلام طلبك بنجاح',
    'company_registration_success_subtitle':
        'يرجى انتظار موافقة الإدارة على حسابك',
    'company_registration_home_cta': 'الصفحة الرئيسية',
    'profile_model': 'عارض',
    'profile_collage': 'كولاج',
    'profile_ugc': 'UGC',
    'profile_gender_label': 'الجنس',
    'profile_gender_male': 'ذكر',
    'profile_gender_female': 'أنثى',
    'profile_basic_title': 'المعلومات الأساسية',
    'profile_basic_subtitle': 'أضف البيانات التي تعرف بحسابك.',
    'profile_name': 'الاسم',
    'profile_name_hint': 'أدخل الاسم',
    'profile_full_name_arabic': 'الاسم الكامل بالعربية',
    'profile_full_name_arabic_hint': 'أدخل الاسم',
    'profile_mawthoq_certificate': 'رقم شهادة موثوق',
    'profile_mawthoq_certificate_hint': 'أدخل رقم الشهادة',
    'profile_full_name': 'الاسم الكامل',
    'profile_full_name_hint': 'أدخل اسمك الكامل',
    'profile_email': 'البريد الإلكتروني',
    'profile_email_hint': 'name@example.com',
    'profile_age': 'العمر',
    'profile_age_hint': '25',
    'profile_country': 'الدولة',
    'profile_country_saudi': 'السعودية',
    'profile_country_uae': 'الإمارات العربية المتحدة',
    'profile_country_egypt': 'مصر',
    'profile_city': 'المدينة',
    'profile_city_hint': 'اختر المدينة',
    'profile_contact_label': 'التواصل',
    'profile_select_hint': 'اختر',
    'profile_required_error': 'هذا الحقل مطلوب',
    'profile_email_error': 'أدخل بريدًا إلكترونيًا صحيحًا',
    'profile_categories_title': 'التصنيفات',
    'profile_categories_subtitle': 'اختر التصنيفات التي تصف محتواك.',
    'profile_main_category': 'التصنيف الرئيسي',
    'profile_category_fashion': 'أزياء',
    'profile_category_beauty': 'جمال',
    'profile_category_food': 'طعام',
    'profile_category_travel': 'سفر',
    'profile_category_tech': 'تقنية',
    'profile_category_sports': 'رياضة',
    'profile_details_title': 'تفاصيل المؤثر',
    'profile_details_subtitle': 'أضف الحي والاتجاه والمدينة.',
    'profile_model_details_title': 'تفاصيل العارض',
    'profile_collage_details_title': 'تفاصيل الكولاج',
    'profile_ugc_details_title': 'تفاصيل UGC',
    'profile_nationality': 'الجنسية',
    'profile_nationality_hint': 'اختر الفئة',
    'profile_size': 'المقاس',
    'profile_size_hint': 'اختر الفئة',
    'profile_skin_tone': 'لون البشرة',
    'profile_skin_tone_hint': 'اختر الفئة',
    'profile_session_rate_per_hour_sar': 'سعر الجلسة لكل ساعة (SAR)',
    'profile_height_cm': 'الطول (سم)',
    'profile_height_cm_hint': 'أدخل الطول',
    'profile_weight_kg': 'الوزن (كجم)',
    'profile_weight_kg_hint': 'أدخل الوزن',
    'profile_skin': 'البشرة',
    'profile_skin_hint': 'اختر الفئة',
    'profile_eye_color': 'لون العين',
    'profile_eye_color_hint': 'اختر الفئة',
    'profile_shoes_size': 'مقاس الحذاء',
    'profile_shoes_size_hint': 'أدخل مقاس الحذاء',
    'profile_modeling_experience': 'سنوات الخبرة في عرض الأزياء',
    'profile_modeling_experience_hint': 'أدخل السنوات',
    'profile_price_per_second_sar': 'سعر الثانية (SAR)',
    'profile_video_price_sar_short': 'سعر الفيديو (SAR)',
    'profile_delivery_time_from_arrival': 'وقت التسليم من وصول المنتج',
    'profile_offer_your_works': 'اعرض أعمالك',
    'profile_voice_over': 'تعليق صوتي',
    'profile_use_hook': 'استخدام هوك',
    'profile_hair_visible': 'إظهار الشعر',
    'profile_face_visible': 'إظهار الوجه',
    'profile_have_visible': 'إظهار التوفر',
    'profile_show_full_body': 'إظهار كامل الجسم',
    'profile_district': 'الحي',
    'profile_district_hint': 'أدخل الحي',
    'profile_direction': 'الاتجاه',
    'profile_direction_hint': 'اختر الاتجاه',
    'profile_direction_opt_north': 'شمال',
    'profile_direction_opt_south': 'جنوب',
    'profile_direction_opt_east': 'شرق',
    'profile_direction_opt_west': 'غرب',
    'profile_direction_opt_central': 'وسط',
    'profile_city_opt_riyadh': 'الرياض',
    'profile_city_opt_jeddah': 'جدة',
    'profile_city_opt_dubai': 'دبي',
    'profile_city_opt_doha': 'الدوحة',
    'profile_city_opt_cairo': 'القاهرة',
    'profile_bio': 'نبذة',
    'profile_bio_hint': 'اكتب نبذة قصيرة عن محتواك',
    'profile_language': 'لغة المحتوى',
    'profile_language_arabic': 'العربية',
    'profile_language_english': 'الإنجليزية',
    'profile_language_both': 'العربية والإنجليزية',
    'profile_social_title': 'حسابات التواصل والتسعير',
    'profile_social_subtitle': 'أضف حساباتك وحدد الأسعار لكل منصة.',
    'profile_username_handle': 'اسم المستخدم / المعرف',
    'profile_username_handle_hint': '@...',
    'profile_story_price_sar': 'سعر القصة (ر.س)',
    'profile_video_price_sar': 'سعر الفيديو (ر.س)',
    'profile_reel_price_sar': 'سعر الريل (ر.س)',
    'profile_post_price_sar': 'سعر المنشور (ر.س)',
    'profile_price_enter_hint': 'أدخل',
    'profile_works_portfolio_title': 'الأعمال والمعرض',
    'profile_works_portfolio_subtitle':
        'ارفع أعمالك ومعرضك لتعرّف العلامات عليك.',
    'profile_portfolio_upload_area_title': 'منطقة رفع المعرض',
    'profile_portfolio_upload_area_desc':
        'أضف فيديوهات أو صور أو مراجع حملات للمعاينة.',
    'profile_browse_files': 'تصفح الملفات',
    'profile_file_skipped_large_one':
        'تم تخطي ملف واحد (أكبر من 5 ميجابايت لكل ملف).',
    'profile_file_skipped_large_many':
        'تم تخطي {count} ملفات (أكبر من 5 ميجابايت لكل ملف).',
    'profile_clients_title': 'العملاء',
    'profile_clients_subtitle': 'العلامات التي تعاملت معها.',
    'profile_clients_empty_title': 'لا توجد بيانات عملاء بعد',
    'profile_add_client': 'إضافة عميل',
    'profile_add_clients_sheet_title': 'إضافة عملاء',
    'profile_search_people_hint': 'ابحث عن الأشخاص',
    'profile_add_clients_with_count': 'إضافة ({count}) عميل',
    'profile_client_cat_sports': 'رياضة',
    'profile_client_cat_entertainment': 'ترفيه',
    'profile_client_cat_beverage': 'مشروبات',
    'profile_client_cat_food': 'طعام',
    'profile_client_cat_clothing': 'ملابس',
    'profile_client_cat_tech': 'تقنية',
    'profile_followers': 'المتابعون',
    'profile_post_price': 'سعر المنشور',
    'profile_story_price': 'سعر القصة',
    'profile_reel_price': 'سعر الريل',
    'profile_currency_hint': 'ر.س',
    'profile_platform_instagram': 'إنستغرام',
    'profile_platform_snapchat': 'سناب شات',
    'profile_platform_tiktok': 'تيك توك',
    'profile_platform': 'المنصة',
    'profile_media_title': 'معرض الأعمال',
    'profile_media_subtitle':
        'أضف نماذج مؤقتة الآن وسيتم ربط الرفع بالواجهة البرمجية لاحقًا.',
    'profile_work_upload_title': 'رفع نماذج الأعمال',
    'profile_work_upload_desc': 'أضف صورًا أو فيديوهات تمثل أعمالك.',
    'profile_add_sample': 'إضافة نموذج',
    'profile_others_title': 'أخرى',
    'profile_preferred_collaboration': 'نوع التعاون المفضل',
    'profile_preferred_contact': 'طريقة التواصل المفضلة',
    'profile_collab_paid': 'مدفوع',
    'profile_collab_barter': 'مقايضة',
    'profile_collab_both': 'كلاهما',
    'profile_contact_whatsapp': 'واتساب',
    'profile_contact_email': 'البريد الإلكتروني',
    'profile_contact_phone': 'الهاتف',
    'profile_ads_title': 'الإعلانات',
    'profile_ads_subtitle':
        'ارفع مقاطع فيديو لإعلانات أو حملات لمعاينة العلامات.',
    'profile_ads_upload_title': 'رفع الإعلانات',
    'profile_ads_upload_desc': 'أضف أمثلة إعلانية لمراجعة العلامات.',
    'profile_ads_upload_dialog_title': 'رفع الإعلانات',
    'profile_ads_dialog_body':
        'اختر ملف فيديو أو أكثر من جهازك. ستظهر كمعاينات أدناه.',
    'profile_ads_browse_videos': 'تصفح الفيديوهات',
    'profile_ads_add_more': 'إضافة المزيد',
    'profile_add_ad': 'إضافة إعلان',
    'profile_cancel': 'إلغاء',
  };

  static String of(Locale locale, String key) {
    if (locale.languageCode == 'ar') {
      return ar[key] ?? en[key] ?? key;
    }
    return en[key] ?? key;
  }
}
